import React from "react";

const Noop = () => null;

export const auroraCurtain = Noop;
export const bokehOrbs = Noop;
export const cardFlipReveal = Noop;
export const coinBurst = Noop;
export const confettiSkia = Noop;
export const crownCombo = Noop;
export const dataStreamRibbons = Noop;
export const digitalNoiseDissolve = Noop;
export const fireworks = Noop;
export const frostedBloom = Noop;
export const glassReveal = Noop;
export const glassRevealSweep = Noop;
export const glitchScanlineSweep = Noop;
export const glowBurst = Noop;
export const glowEdgeTrace = Noop;
export const gridMagnifyPulse = Noop;
export const hologramFlicker = Noop;
export const inkSpread = Noop;
export const lightning = Noop;
export const liquidLensRipple = Noop;
export const matrixRainDepthSweep = Noop;
export const matrixSweep = Noop;
export const metaballBlob = Noop;
export const metaballBlobMorph = Noop;
export const metaballTypographyReveal = Noop;
export const neonWireframeGridWarp = Noop;
export const oilSlickFilm = Noop;
export const orbitRing = Noop;
export const pixelSortSwipe = Noop;
export const prismaticRefraction = Noop;
export const ribbonSweep = Noop;
export const softHearts = Noop;
export const softSpotlightSweep = Noop;
export const sparkleRain = Noop;
export const starburst = Noop;
export const terminalTypewriterBurst = Noop;
export const typographyMetaball = Noop;
export const viscousDripPull = Noop;
